version: '3.8'

services:
  substrate-proxy:
    image: uniquenetwork/substrate-proxy-http-proxy:master
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - CHAIN=ws://assethub-chopsticks:8002
      - MIN_LOG_LEVEL=info
      - EXTRINSIC_MORTAL_BLOCK_LENGTH=32
      - OPENAPI_SERVER_URL=http://localhost:3002
      - OPENAPI_SERVER_DESCRIPTION="Local development server"
      - EXTRINSICS_STORAGE_MAX_BLOCKS_COUNT=100
    restart: always
    depends_on:
      - assethub-chopsticks
    networks:
      - backend

  assethub-chopsticks:
    container_name: assethub-chopsticks
    build:
      context: .
      dockerfile: ./Dockerfile
      target: assethub
    environment:
      - PORT=8002
    ports:
      - "8002:8002"
    networks:
      - backend

networks:
  backend:
    driver: bridge
